export default {
  id: 'model-1',
  type: 'root',
  name: 'design-model',
  children: [
    {
      id: 'test-1',
      name: 'text-1',
      type: 'text',
      textAlign: 'center',
      text: 'Your paragraph text',
      fontFamily: 'Arial',
      fontSize: 26,
      // spacing: 10,
      width: 200,
      height: 200,
      x: 27,
      y: 48,
    },
    // {
    //   id: 'test-2',
    //   name: 'text-2',
    //   type: 'text',
    //   textAlign: 'center',
    //   text: 'How are You !',
    //   fontFamily: 'Arial',
    //   fontSize: 26,
    //   // spacing: 10,
    //   width: 200,
    //   height: 200,
    //   x: 127,
    //   y: 348,
    // },
  ],
}
